name: landing
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.1
  flutter_native_splash: ^2.3.11
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  go_router: ^13.1.0
  http: ^1.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash2.png
  android: true
  ios: true
  web: true

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: AllianceNo2
      fonts:
        - asset: assets/fonts/AllianceNo2-Light.ttf
          weight: 300
        - asset: assets/fonts/AllianceNo2-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/AllianceNo2-Regular.ttf
          weight: 400
        - asset: assets/fonts/AllianceNo2-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/AllianceNo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/AllianceNo2-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/AllianceNo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AllianceNo2-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/AllianceNo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/AllianceNo2-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AllianceNo2-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AllianceNo2-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/AllianceNo2-Black.ttf
          weight: 900
        - asset: assets/fonts/AllianceNo2-BlackItalic.ttf
          weight: 900
          style: italic
